### ISSUE TITLE
Couldn't open the Marker's Popup by default

### ISSUE THREAD

**Issue by loq24** [masotime/react-leaflet-universal#13]
I tried to create a my own Marker class that extends the original Marker component to be able to open the Marker's Popup by default. [This is how it was done.](https://stackoverflow.com/a/38971299/1733530) But **this.leafletElement** is undefined. Please help.

**Comment by masotime** [comment]
So this won't work. The wrappers intentionally wait until after the component is mounted, then waits another render cycle before the actual component is available.

You will either need to use `leafletRef` and wait until the `ref` is ready before doing any operation, or you must manually write your own decorator around `Marker` which wraps rather than extends it.
