### ISSUE TITLE
Missing export for Icon

### ISSUE THREAD

**Issue by gurre** [masotime/react-leaflet-universal#15]
There is a missing export for Icon.

https://leafletjs.com/reference-1.4.0.html#icon

**Comment by masotime** [comment]
This module is just a wrapper around [react-leaflet](https://github.com/PaulLeCam/react-leaflet) - unfortunately React leaflet itself doesn't export `Icon`. The suggested usage seems to be as described https://github.com/PaulLeCam/react-leaflet/blob/master/example/components/custom-icons.js.

Does that work for you? There might be issues since you would be attempting `L.Icon` server-side.

**Comment by gurre** [comment]
Yes, it's unfortunate. `import L from 'leaflet'` requires that the window variable is present so that I can't use with server-side rendering. I've managed to solve my issue. Thank you, great library!

**Comment by devictoribero** [comment]
@gurre:
1- Did you finally use the icon using the server-side? How?
2- How do you load your leaflet styles though?

I'm using NextJS and If I add the styles on the page by using `next/head` when I visit that page in the client-side the marker is not loading.

**Comment by gurre** [comment]
> @gurre:
> 1- Did you finally use the icon using the server-side? How?
> 2- How do you load your leaflet styles though?
> 
> I'm using NextJS and If I add the styles on the page by using `next/head` when I visit that page in the client-side the marker is not loading.

I wasn't using nextjs but I solved it using a simple conditional on window.
