### ISSUE TITLE
LayersControl Error

### ISSUE THREAD

**Issue by jpserrett** [masotime/react-leaflet-universal#8]
I am getting an error when attempting to use LayersControl.BaseLayer or LayersControl.Overlay. 
```
 <Map center={ [51.505, -0.09] } zoom={ 13 } id="leaflet-map">
    <TileLayer url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/>
    <LayersControl position="topright">
        <LayersControl.Overlay checked name="testBaseLayer">
           <GeoJSON data={ this.state.geoJson } />
        </LayersControl.Overlay>
     </LayersControl>
 </Map>
```

And this is the error I'm getting: 

> Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.

I've checked and the error only happens for the LayersControl.BaseLayer and Overlay. Are these not supported or am I doing something incorrectly? 

Thanks in advance for your help.

**Comment by masotime** [comment]
Thanks @jpserrett . It's not hard to guess the issue - the problem is that the universal versions are just wrappers over the normal ones, and they don't contain the "static" properties.

This is a very simplified example, but it's roughly correct:
```
class A {
  static class B {
  }
}

class WrappedA {
  render() {
    return <A>
  }
}
```

WrappedA.B will not exist, because it doesn't know that A has B. I'm not sure if I can access A.B on the server though. I'll need to dig deeper into the code.
